name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -p starpls --release
      - uses: actions/upload-artifact@v4
        with:
          name: starpls-windows-amd64
          path: target/release/starpls.exe

  release:
    name: Release
    needs: [build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: starpls-*
      - name: Prepare release artifacts
        run: |
          mkdir -p release
          mv artifacts/starpls-windows-amd64/starpls.exe release/starpls-windows-amd64.exe
      - name: Show release artifacts
        run: find release
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} release/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
